### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by oeuillot**
Add a simple http proxy support.

### CODE REVIEW

**Comment by leeroybrun** [comment]
Great, thanks! Which proxy are you using with this ?

**Comment by oeuillot** [comment]
A free proxy ;-)

http://www.freeproxylists.net/fr/

Regards,

Olivier

2015-04-29 14:50 GMT+02:00 Leeroy Brun <notifications@github.com>:

**Comment by oeuillot** [comment]
Cool thanks, can you publish a new npm distrib ?

**Comment by leeroybrun** [comment]
Sure, it's already done :-) v0.1.7 is available on npm.

**Pull request merged**
